[COR-293] return variance on totp comparison
beaconsoftwarellc/gadget pull request #24
Opened 2022-04-25 14:28 UTC by morus12

Return variance on TOTP comparison.

2022-04-25 18:32 UTC, apynes approved these changes
Suggestion on naming, otherwise LGTM :+1:

2022-04-25 18:45 UTC, apynes requested changes
Need to accept drift as a parameter

2022-04-25 18:45 UTC, apynes commented on crypto/totp.go
> +func TOTPCompareAndGetVariance(key string, period time.Duration, length int, variance uint, challenge string) (bool, int, error) {
Didn't notice earlier, this needs to accept the drift as a parameter to center the comparison window on

2022-04-25 19:55 UTC, nmarie22 approved these changes

2022-04-26 01:31 UTC, apynes requested changes
I think you may have missed my comment that I requested changes about. Added some more clarification. Let me know if this still is not making sense.

2022-04-26 01:31 UTC, apynes commented on crypto/totp.go
> +func TOTPCompareAndGetDrift(key string, period time.Duration, length int, variance uint, challenge string) (bool, int, error) {
```suggestion
func TOTPCompareAndGetDrift(key string, period time.Duration, length int, variance uint, challenge string, drift int) (bool, int, error) {
```

2022-04-26 01:31 UTC, apynes commented on crypto/totp.go
>  	for vary := 0; vary <= int(variance); vary++ {
we want to skew this using the drift passed in, so if we have the values we would want to check the frames according to this:
```
drift   variance  frames
0       0              0
0       1              -1,0,1
0       2              -2,-1,0,1,2
1       1              0,1,2
1       2              -1,0,1,2,3
-1      1              -2,-1,0
-1      2              -3,-2,-1,0,1
```

2022-04-27 13:54 UTC, apynes requested changes
Looks good, just need some changes around the frame constructions and this will be good to go

2022-04-27 13:54 UTC, apynes commented on intutil/math.go
> +func Abs[T constraints.Signed](a T) T {
missing test

2022-04-27 13:54 UTC, apynes commented on intutil/math.go
> +func Minv[T constraints.Ordered](ints ...T) T {
missing tests for this one as well

2022-04-27 13:54 UTC, apynes commented on crypto/totp.go
> +	})
we need to center the variance on the drift, we may want this in a separate function that can be tested.

2022-04-27 13:54 UTC, apynes commented on crypto/totp.go
> +	slices.SortFunc(vary, func(a, b int) bool {
kind of annoying that they did not make the sort functions fluent, but oh well.

2022-04-28 18:55 UTC, apynes approved these changes
LGTM :+1:

2022-04-28 18:56 UTC, merged