COR-404 foregin key error translation
beaconsoftwarellc/gadget pull request #29
Opened 2022-07-31 20:03 UTC by morus12

2022-08-01 14:06 UTC, apynes approved these changes
typo, other than that it looks good

2022-08-01 14:06 UTC, apynes commented on database/errors_test.go
> +			name:     "foregin key",
```suggestion
			name:     "foreign key",
```

2022-08-01 20:37 UTC, nmarie22 requested changes

2022-08-01 20:37 UTC, nmarie22 commented on database/errors.go
> +		err = status.Error(codes.InvalidArgument, fmt.Sprintf("%s %s foregin key violation: %s",
Same typo here

2022-08-02 19:41 UTC, nmarie22 approved these changes

2022-08-02 19:42 UTC, merged

2022-08-02 19:42 UTC, nmarie22 commented
@morus12 change is ready to be released and version updated on core and connect