[CON-718] bitwise operators
beaconsoftwarellc/gadget pull request #36
Opened 2022-10-21 22:08 UTC by morus12

2022-10-24 14:00 UTC, nmarie22 requested changes

2022-10-24 14:00 UTC, nmarie22 commented on sliceutil/anonymize_test.go
> +	t.Run("ints", func(t *testing.T) {
This isn't actually testing ints

2022-10-24 14:46 UTC, nmarie22 submitted a review, later dismissed

2022-10-24 16:12 UTC, apynes requested changes
Some small changes and we need tests for the other query types, specifically Update since that is what the ticket is ultimately for.

2022-10-24 16:12 UTC, apynes commented on database/qb/expression.go
> +	cond  *ConditionExpression
this should just be `binaryExpression`

2022-10-24 20:17 UTC, apynes requested changes
Minor things

2022-10-24 20:17 UTC, apynes commented on sliceutil/anonymize.go
> +func String[T ~string](src []T) []string {
missing documentation on a public function

2022-10-24 20:17 UTC, apynes commented on sliceutil/anonymize.go
> +func String[T ~string](src []T) []string {
This should be called "Strings" or "ToStrings" or "ToStringSlice" or something similar. `.String` means give me a string representation of the object, e.g. `String([]int{1,2,3}) => "[ 1, 2, 3 ]" `

2022-10-25 19:51 UTC, apynes approved these changes

2022-10-25 20:53 UTC, nmarie22 approved these changes

2022-10-26 06:15 UTC, merged