COR-544 message attribute name validator
beaconsoftwarellc/gadget pull request #41
Opened 2022-11-23 22:04 UTC by morus12

2022-11-28 21:36 UTC, apynes commented
This needs to be merged and the conflicts resolved before it can be properly reviewed.

2022-11-29 16:47 UTC, apynes commented
> This needs to be merged and the conflicts resolved before it can be properly reviewed.

@morus12 ^^^

2022-11-29 21:39 UTC, apynes requested changes
just one minor change, otherwise LGTM :+1:

2022-11-29 21:39 UTC, apynes commented on messagequeue/sqs/validation.go
> +	bodyMinimumError = errors.New("minimum character count is 1")
we don't want to initialize the error here because then the stack trace is static and will not be useful for whoever logs it.

2022-11-30 14:38 UTC, nmarie22 approved these changes

2022-12-01 15:04 UTC, merged