[COR-545] validate sqs body
beaconsoftwarellc/gadget pull request #42
Opened 2022-11-24 22:47 UTC by morus12

2022-11-30 14:39 UTC, nmarie22 approved these changes

2022-12-01 15:54 UTC, apynes requested changes
disambiguation of Kibi and Kilo. The requirements are for 256 Kibibytes (JEDEC Kilobytes) not Kilobytes.
Also, we can clean up a error message to be more clear.

2022-12-01 15:54 UTC, apynes commented on messagequeue/sqs/validation.go
> +	if len(s) > maxBodyKilobytes*1000 {
```suggestion
	if len(s) > maxBodyKibibytes*1024 {
```

2022-12-01 15:54 UTC, apynes commented on messagequeue/sqs/validation.go
> +	maxBodyKilobytes  = 256
```suggestion
	maxBodyKibibytes  = 256
```

2022-12-01 15:54 UTC, apynes commented on messagequeue/sqs/validation.go
> +		return errors.New("body cannot exceed %d kilobytes (was %d bytes)", maxBodyKilobytes, len(s))
```suggestion
		return errors.New("body cannot exceed %d KiB (was %d bytes)", maxBodyKibibytes, len(s))
```

2022-12-01 15:54 UTC, apynes commented on messagequeue/sqs/validation.go
> +			return errors.New("char 0x%x is not allowed unicode character", r)
```suggestion
			return errors.New("body cannot contain forbidden unicode character 0x%x", r)
```

2022-12-02 16:15 UTC, apynes approved these changes

2022-12-02 16:15 UTC, merged