[COR-504] changes to support local development via docker
beaconsoftwarellc/gadget pull request #51
Opened 2023-01-19 19:00 UTC by apynes

2023-01-20 21:46 UTC, nmarie22 submitted a review, later dismissed

2023-01-20 22:18 UTC, webpro-jjaynes requested changes

2023-01-20 22:18 UTC, webpro-jjaynes commented on messagequeue/sqs/endpointresolver_test.go
> +		generator.String(5), generator.String(5))
```suggestion
		ServiceName, generator.String(5))
```

2023-01-20 22:18 UTC, webpro-jjaynes commented on messagequeue/sqs/endpointresolver_test.go
> +		generator.String(5), generator.String(5))
Doesn't the service name need to be valid to allow you to test the endpoint not being found vs. invalid service provided?

2023-01-20 23:00 UTC, webpro-jjaynes approved these changes

2023-01-21 12:51 UTC, anthonyheidenreich approved these changes

2023-01-21 17:46 UTC, merged