[COR-654] Don't keep reporting the same Slow Queries
beaconsoftwarellc/gadget pull request #57
Opened 2023-04-17 17:06 UTC by nmarie22

2023-04-17 21:09 UTC, webpro-jjaynes requested changes

2023-04-18 13:22 UTC, nmarie22 commented on database/transaction/slowquerylogger.go
> +	if ok && logged <= elapsed {
Most definitely, thanks :1st_place_medal:

2023-04-18 13:48 UTC, webpro-jjaynes approved these changes

2023-04-19 18:29 UTC, apynes requested changes
This will only limit logging within a single transaction. We will need push the cache up to the `InstanceConfig` and inject into the transaction on initialization.

2023-04-20 15:19 UTC, apynes approved these changes

2023-04-20 17:42 UTC, merged